### ISSUE TITLE
Documentation references to facebook/parler_tts-small

### ISSUE THREAD

**Issue by rsxdalv** [huggingface/parler-tts#117]
Docstrings contain broken code examples, such as:

https://github.com/huggingface/parler-tts/blob/8e465f1b5fcd223478e07175cb40494d19ffbe17/parler_tts/modeling_parler_tts.py#L2610

My research suggests that parler was never Facebook's TTS model; however the documentation has facebook/parler_tts-small references in several places.

This will not work: `ParlerTTSForConditionalGeneration.from_pretrained("facebook/parler_tts-small")` and it should be for example: parler-tts/parler-tts-mini-v1

**Comment by ylacombe** [comment]
Hey @rsxdalv, thanks for opening this issue! Feel free to open a PR to fix this, if you have time!
