### ISSUE TITLE
[Documentation Contribution] Voice consistency

### ISSUE THREAD

**Issue by ylacombe** [huggingface/parler-tts#130]
There's been an effort to introduce voice consistency as explained [here](https://github.com/huggingface/parler-tts/issues/95). It'd be great to open a PR to write about it the README.md or the INFERENCE.md, who would like to tackle this?

**Comment by lunakhan** [comment]
I would like to work on this!

**Comment by bhargavyagnik** [comment]
Hi @lunakhan are you taking this up? or can I do it.
