### ISSUE TITLE
garbled audio

### ISSUE THREAD

**Issue by toninog** [huggingface/parler-tts#161]
Hi

Not sure why, but when I run either of the example code - I get garbled audio - when I use the Mini Model I get the "correct" audio

I have the following setup

Ubuntu 22.04
Python 3.11.4

 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

python3 -m pip show torch
Name: torch
Version: 2.5.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /data/parler-tts/.venv/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: descript-audio-codec, descript-audiotools, julius, parler_tts, torch-stoi, torchaudio

Thanks

**Comment by SummerXIATIAN** [comment]
same here, any solutions?

**Comment by wizche** [comment]
same here, mini model works, large model generates just noise.
Debian 11 / python 3.9.2, Cuda 12.6, torch 2.5.1

**Comment by DerXter** [comment]
same here too, but with the mini model, my `audio_arr` vector get always a length of 5632. When the sample rate is then applied, the audio duration drops to 0. Could someone help me solve this issue please !?

**Comment by FireMMDC** [comment]
Looking at this thread #157 it seems like maybe the change of the transformers version might have broken the larger model's inferencing, using 5d0aca9753ab74ded179732f5bd797f7a8c6f8ee I was able to generate audio using the larger model.

**Comment by sswam** [comment]
This issue seems important, the large model just does not work. I suggest to use a test suite, and run the output through whisper or something.

**Comment by ylacombe** [comment]
Hey everyone, thanks for opening the issue and helping on identifying where it blocks.

It actually comes from the audio encoder. While I still have to figure out how to actually fix it while being backward compatible for person using it with the previous repo version, you can find fixed weights for the current version by using:
model = ParlerTTSForConditionalGeneration.from_pretrained("parler-tts/parler-tts-large-v1", revision= "refs/pr/9")

**Comment by toninog** [comment]
Amazing @ylacombe  - this fixed things perfectly!
