### ISSUE TITLE
sampling rate issue

### ISSUE THREAD

**Issue by jasonppy** [huggingface/parler-tts#23]
Great work!

When running the DAC token extraction stage of the training script with the default hyperparams, I got warning:

> It is strongly recommended to pass the `sampling_rate` argument to this function. Failing to do so can result in silent errors that might be hard to debug.

I checked the `feature_extractor.sampling_rate` which got passed to `load_multiple_datasets` and it's indeed 44100Hz. 

Just want to make sure this is expected.

Thanks!

**Comment by ylacombe** [comment]
Hey @jasonppy, this is expected! You got the sampling rate right!
