### ISSUE TITLE
Save checkpoints as usable models

### ISSUE THREAD

**Issue by deguodedongxi** [huggingface/parler-tts#37]
Hey everyone, 

I am trying to fine-tune a model. I ran into overfitting after some training. Now I want to save a previous checkpoint as my model. As far is a can see, you are using safetensor models when using the "ParlerTTSForConditionalGeneration.from_pretrained()" method.

I cannot find an easy way how to load and save a checkpoint without starting a new training. Do you have any suggestions?

Thank you :)

**Comment by ylacombe** [comment]
Hey @deguodedongxi, you should simply copy the `config.json` and `generation_config.json` to the checkpoint folder you want, then you can load the model using the checkpoint folder path as your model name! let me know if that helps

**Comment by ylacombe** [comment]
Have you been able to save the checkpoints as you wanted @deguodedongxi ?

**Comment by deguodedongxi** [comment]
Sorry, I haven't answered. It worked, yes. Thanks for your help!

My training data was too small, so the result was not good enough, but thats another story ;)
