### ISSUE TITLE
Descript Audio Codec selection

### ISSUE THREAD

**Issue by yuan1615** [huggingface/parler-tts#42]
The current model selected is the 44khz model, and there are 9 codebooks here. However, according to the test at [Codec-SUPERB](https://github.com/voidful/Codec-SUPERB), it can be seen that the decoder of the 24khz model with 32 codebooks performs better. Is it possible to replace 9 codebooks with 32 codebooks? If so, will it be difficult to train a decoder-only model?

**Comment by ylacombe** [comment]
Hey @yuan1615, thanks for sharing the benchmark, I wasn't aware of i!
Training from-scratch for this is totally feasible, but 32 code-books seems like a lot, as the model would use 32 embedding layers and 32 LM heads. Additionally, the benchmark doesn't seem to use subjective metrics, so it might be non conclusive!

**Comment by yuan1615** [comment]
Thank you for the reply, I also feel that using 32 seems a bit excessive.
