### ISSUE TITLE
Exception in label generated

### ISSUE THREAD

**Issue by MingHui-Fang** [huggingface/parler-tts#63]
Hello, I followed the training guide and trained a parlerTTS model from scratch. First I initialized a new mod using 
```
python helpers/model_init_scripts/init_dummy_model.py ./parler-tts-untrained-dummy --text_model "google-t5/t5-small" --audio_model "parler-tts/dac_44khZ_8kbps
```
After that, I referred to the parameters provided in the training guide and modified the tokenizer slightly to match the model,  Specifically, this includes 
```
--description_tokenizer_name "google-t5/t5-small" \
--prompt_tokenizer_name "google-t5/t5-small" \
```
At the same time I modified the batch size to initiate training.
However, there seems to be an error in generating the labels, where two of the nine channels are completely populated with 1024 (i.e. pad_token/eos_token), is this situation stemming from the model not being adequately trained?
I've attached an image showing the results generated.
![WechatIMG5880](https://github.com/huggingface/parler-tts/assets/87628840/8fa1cb50-7a37-489d-a006-4179bde33202)

**Comment by MingHui-Fang** [comment]
Meanwhile I ran into a second problem, I'm using the officially provided training tutorial and I'm encountering error reporting when executing the `forward` function of the `ParlerTTSSinusoidalPositionalEmbedding` class.

My code will execute up to this point: 
https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/parler_tts/modeling_parler_tts.py#L221-L222

Then the error message is 
```
AttributeError: 'ParlerTTSSinusoidalPositionalEmbedding' object has no attribute 'offset'
```

How should `self.offset` be defined and can I take any value?

**Comment by ylacombe** [comment]
Hey @MingHui-Fang, thanks for opening the issue, this is indeed a weird error. could you send a reproducing code snippet with regards to your first error and send more details on what you exactly did ? What you did does seem correct to me.

For the offset thing, there's definitely a bug with the offset missing! 
You can have a workaround either by chunking your audio to chunks less than 30s or by setting a longer context window here:https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/helpers/model_init_scripts/init_model_600M.py#L27

**Comment by MingHui-Fang** [comment]
Sincerely thank you for your answer, the first problem I have solved, I found out that it is because of using wrong generation_config.json when generating. 

secondly in the second problem, there may be some problem in the code to initialize tiny-model ([init_dummy_model.py](https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/helpers/model_init_scripts/init_dummy_model.py#L27)) as below:

https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/helpers/model_init_scripts/init_dummy_model.py#L27

and 

https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/helpers/model_init_scripts/init_dummy_model.py#L60

Now, I have successfully completed the training as well as the inference process using tiny-model, although the sound quality of the generated audio is a bit poor, but I guess that's a separate issue. Thanks again for your reply and the code.
