### ISSUE TITLE
LM Output Vocab Size and Extra Tokens

### ISSUE THREAD

**Issue by QajikHakobyan** [huggingface/parler-tts#64]
Thanks for the fantastic work on this project!

I'm reviewing your code and noticed something about the language model's output vocabulary size. It seems to be set to encodec_vocab_size + 64. However, my understanding is that the LM generates tokens only from the encodec vocabulary, along with a single end_of_sequence token. If that's correct, wouldn't the necessary vocabulary size be encodec_vocab_size + 1?

I'm curious about the purpose of the additional 63 tokens in the output vocabulary. Could you please clarify why this is the case?

**Comment by ylacombe** [comment]
Hey @QajikHakobyan, nice catch.
There are two reasons for this:
1. You might want to add some additional tokens in your vocabulary. This provides some free slots if you need it.
2. There's supposed to be some GPU speed-ups in training/inference if your weights are multiple of power of 2s. In practice I didn't observe any at this model size so you can probably set `encodec_vocab_size + 1`.
