### ISSUE TITLE
Error: Assertion `srcIndex < srcSelectDimSize` failed

### ISSUE THREAD

**Issue by chunping-xt** [huggingface/parler-tts#66]
I initialized  models from scratch, because flan-t5 doesn't support my language: 
!python helpers/model_init_scripts/init_dummy_model.py ./parler-tts-untrained-dummy_1 --text_model "google-t5/t5-small" --audio_model "parler-tts/dac_44khZ_8kbps"
!python helpers/model_init_scripts/init_dummy_model.py ./parler-tts-untrained-dummy_2 --text_model "google/flan-t5-base" --audio_model "parler-tts/dac_44khZ_8kbps"

when train I get the same error:

Step... (100 / 8280 | Loss: 6.848744869232178, Learning Rate: 1.6000000000000003e-05)
Step... (200 / 8280 | Loss: 6.750528812408447, Learning Rate: 3.2000000000000005e-05)
Step... (300 / 8280 | Loss: 6.650070667266846, Learning Rate: 4.8e-05)          
Step... (400 / 8280 | Loss: 6.698696613311768, Learning Rate: 6.400000000000001e-05)
Step... (500 / 8280 | Loss: 6.726866245269775, Learning Rate: 8e-05)            
Train steps ... :   6%|█▏                  | 500/8280 [05:34<1:28:30,  1.47it/s]

Evaluating - Inference ...:   0%|                         | 0/1 [00:00<?, ?it/s]

Evaluating - Inference ...: 100%|█████████████████| 1/1 [00:00<00:00,  3.24it/s]

Evaluating - Generation ...:   0%|                        | 0/1 [00:00<?, ?it/s]../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1236: indexSelectSmallIndex: block: [2,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by MingHui-Fang** [comment]
Models generated using the `helpers/model_init_scripts/init_dummy_model.py` will have out-of-range issues during the generation phase due to configuration.
You can refer to [this answer](https://github.com/huggingface/parler-tts/issues/63#issuecomment-2154460402), adjust `max_position_embeddings` or `model.generation_config.max_length`.
According to the official code provided, the position embedding for 30s should be set to 2580.
