### ISSUE TITLE
How do you change the sampling rate while keeping the sound quality roughly the same?

### ISSUE THREAD

**Issue by milkyfun0** [huggingface/parler-tts#70]
I want to change "sampling_rate": 44100 to 16000Hz but modifying the preprocessor_config.json file won't work, thanks

**Comment by sanchit-gandhi** [comment]
Hey @milkyfun0 - we need to match the sampling rate to that of our codec model. In this case, we use the DAC 44.1kHz checkpoint, so need to match the sampling rate to that. If we use a different sampling rate to pre-process our inputs, we're going to get unexpected results, _c.f._ https://huggingface.co/learn/audio-course/en/chapter1/audio_data#sampling-and-sampling-rate

**Comment by milkyfun0** [comment]
> Hey @milkyfun0 - we need to match the sampling rate to that of our codec model. In this case, we use the DAC 44.1kHz checkpoint, so need to match the sampling rate to that. If we use a different sampling rate to pre-process our inputs than that of our codec model, we're going to get unexpected results, _c.f._ https://huggingface.co/learn/audio-course/en/chapter1/audio_data#sampling-and-sampling-rate
> 
> If you want to use a different target sampling rate, you can pick a different DAC checkpoint, and update the sampling rate accordingly, _.c.f._ https://github.com/descriptinc/descript-audio-codec#weights

Thank you for your answer and wish you all the best in your work
