### ISSUE TITLE
GPU parallel

### ISSUE THREAD

**Issue by netagl** [huggingface/parler-tts#71]
Hi,
is there an option to train the model on multiple GPUs?

If not, is there an easy way to addapt it?

tnx!

**Comment by sanchit-gandhi** [comment]
Hey @netagl - scaling to multiple GPUs using [distributed data parallelism (DDP)](https://pytorch.org/tutorials/beginner/ddp_series_theory.html) is trivial: simply run `accelerate config` from the command line and select the multi-GPU option, specifying the IDs of the GPUs you wish to use. You can then use exactly the same configs as in the [training README](https://github.com/huggingface/parler-tts/tree/main/training), and accelerate will automatically scale training to multiple GPUs.

**Comment by netagl** [comment]
Hi @sanchit-gandhi  :)
Thank you for the quick response! I changed the  accelerate config and selcted multi-gpu option, 

This is my accelerator config:

`{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  "enable_cpu_affinity": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "bf16",
  "num_machines": 1,
  "num_processes": 1,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
`

And this is the Error I get:

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 404 405
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

**Comment by MingHui-Fang** [comment]
I ran into the same problem when I tried to modify the model architecture before, this is because the network structure defined in the model using `self.xxx` is not being used (i.e. no gradient for backpropagation).
I've tried two options to solve this problem.
The first one checks all unused networks defined by `self.xxx`and removes them.
The second is to modify the Accelerator's parameters, Specifically to modify here.
https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/training/run_parler_tts_training.py#L100
``` python
from accelerate.utils import DistributedDataParallelKwargs
kwargs_handlers = [
    InitProcessGroupKwargs(timeout=timedelta(minutes=60)),
    DistributedDataParallelKwargs(find_unused_parameters=True)
]
```

**Comment by netagl** [comment]
@MingHui-Fang 
thank you for your answer, did any of this options worked?

**Comment by MingHui-Fang** [comment]
> @MingHui-Fang thank you for your answer, did any of this options worked?

Actually, you can simply add `DistributedDataParallelKwargs(find_unused_parameters=True)` for quick validation, which will consume only a minimal amount of time. At least both of these options have worked for me.

**Comment by netagl** [comment]
I tried, It caused other problems @MingHui-Fang @sanchit-gandhi 
Any way, I found a fc layer that I didnt use, and that caused the problem

tnx!!
