### ISSUE TITLE
Different sample rate

### ISSUE THREAD

**Issue by W-W-H** [huggingface/parler-tts#78]
Hello, I want to train a  new parler model from scratch. Upon reviewing the training readme, it appears that the Parler Mini was trained using LibriTTS R (24kHz) and librispeech(maybe 16000Hz?) but the audio codec employed was DAC (44kHz). Shall I just upsample the datasets to 44khz?

**Comment by milkyfun0** [comment]
https://github.com/huggingface/parler-tts/issues/70
