### ISSUE TITLE
HfHubHTTPError when finetuning

### ISSUE THREAD

**Issue by iakovialexiou** [huggingface/parler-tts#90]
I'm trying to run the code from this [Colab](https://colab.research.google.com/github/ylacombe/scripts_and_notebooks/blob/main/Finetuning_Parler_TTS_on_a_single_speaker_dataset.ipynb)
notebook which calls the training script from ParlerTTS and I get the following error
```
huggingface_hub.utils._errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/datasets/ylacombe/jenny-tts-6h-tagged (Request ID: Root=1-66a52066-71972f3e210bcd0c4d252223;fc1aef1f-e20e-417b-b00a-8fe47be13bf6)

Internal Error - We're working hard to fix this as soon as possible!
```
It looks like the HTTP call to "ylacombe/jenny-tts-6h-tagged" cannot be executed. How can I fix it?
Thank you.

**Comment by ylacombe** [comment]
Sometimes, the hub is done, I think it should work again now!

**Comment by iakovialexiou** [comment]
yes it does, thank you!

**Comment by ylacombe** [comment]
Great! Closing for now!
