### ISSUE TITLE
Alltalk Integration & 1x question re voice consistency

### ISSUE THREAD

**Issue by erew123** [huggingface/parler-tts#96]
Hi 

Congratulations on releasing the V1 update. I've integrated the v1 update into AllTalk v2 BETA https://github.com/erew123/alltalk_tts/tree/alltalkbeta

If you are ever interested in making any updates to the setup for AllTalk I happily welcome them and the engine for Parler is here https://github.com/erew123/alltalk_tts/tree/alltalkbeta/system/tts_engines/parler

Through AllTalk there is a full AllTalk API suite, OpenAI v1 TTS API compatible endpoint and integration to Text-gen-webui, kobold and Sillytavern, as well as things like HomeAssistant via the OpenAI compatible API.

**My 1x question is** How similar should the "Using a specific speaker" consistency be? And does the consistency vary by model?

If it matters to my question, here is how I have setup the voices https://github.com/erew123/alltalk_tts/blob/alltalkbeta/system/tts_engines/parler/parler_voices.json with the "Native" ones being the inbuilt voices.

![image](https://github.com/user-attachments/assets/22120032-894b-4040-a715-8c8b92c1bd3a)
![image](https://github.com/user-attachments/assets/6a0f96b9-0385-4d2f-a02d-1ecc83a3cf32)
![image](https://github.com/user-attachments/assets/94a89df5-af3d-43d9-a6c7-ceb72e19f12a)
![image](https://github.com/user-attachments/assets/3c5a7320-ec32-48b0-9ea4-c0c1008512fa)
![image](https://github.com/user-attachments/assets/407eaebe-b858-44cd-8d9d-ddbdc61fc196)

Thanks

**Comment by ylacombe** [comment]
Hey there, I'm not sure to have truly understand what you want, but feel free to refer to this message: https://github.com/huggingface/parler-tts/issues/95#issuecomment-2285798102

Hope it helps !

**Comment by erew123** [comment]
@ylacombe Thanks for the reply. Yes that should answer my question. To clarify, I was trying to understand how consistent (similar) the list of "built-in" voices should be, between subsequent TTS generations e.g. If I use the same built in voice from the list for 2x TTS generations e.g. "Laura's voice is....xxxxxx", should both of the 2x TTS generations sound **very similar** and be distinguishable as  Laura's voice.

Thanks
